Todo_App/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Todo_App.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Todo_App/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using Todo_App.Model;
using Todo_App.Repository;

namespace Todo_App.Pages
{
    public class IndexModel : PageModel
    {

       

        private readonly ITaskRepo _repo;

        public List<To_Do> ToDoList { get; set; }

        [BindProperty, MaxLength(50), Required]
        public string Title { get; set; }

        [BindProperty, MaxLength(25), Required]
        public string Desc { get; set; }

        [BindProperty]
        public DateTime Created { get; set; }

        [BindProperty, Range(0, 2)]
        public int prio { get; set; }

        [BindProperty]
        public bool IsDone { get; set; }

        [BindProperty]
        public Guid GUid { get; set; }

        public bool ErrorTriggered { get; set; }
        public bool Success { get; set; }
        public IndexModel(ITaskRepo repo)
        {
            _repo = repo;
            ToDoList = repo.GetallTask();
        }

        public void OnGet(string status)
        {
           
            switch (status)
            {
                case "error":
                    ErrorTriggered = true;
                    break;
                default:
                    Success = true;
                    break;
            }
        }
        public IActionResult OnPostAdd()
        {

            GUid = Guid.NewGuid();
            if (ModelState.IsValid)
            {
                _repo.AddTask((To_Do.Priority)prio, Title, Desc, Created);
                return RedirectToPage();
            }
            else
            {
                ErrorTriggered = true;
                return RedirectToPage("Index", new { status = "error" });
            }

        }
        public IActionResult OnPostEdit()
        {
            if (ModelState.IsValid)
            {
                _repo.EditTask(GUid.ToString(), Desc, Title, prio, IsDone);
                return RedirectToPage("index", new { status = "success" });
            }
            else
            {
                ErrorTriggered = true;
                return RedirectToPage("Index", new { status = "error" });
            }
        }
        public IActionResult OnPostComp()
        {
            _repo.CompTask(GUid.ToString());
            return RedirectToPage();
        }
        public IActionResult OnPostDelete()
        {
            _repo.DelTask(GUid.ToString());
            return RedirectToPage();
        }

        public IActionResult OnPostDelAll()
        {
            _repo.DelAll();
            return RedirectToPage();
        }
    }
}

Todo_App/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using Todo_App.Model;
using Todo_App.Repository;

namespace Todo_App.Pages
{
    public class LoginModel : PageModel
    {
        private readonly IUserRepo _repo;
        private readonly List<Users> _userss;

        [BindProperty, Required]
        public string Username { get; set; }

        [BindProperty, Required]
        public string Password { get; set; }
        [BindProperty]
        public string FirstName { get; set; }

        [BindProperty]
        public string LastName { get; set; }

        public LoginModel(IUserRepo repo)
        {
            _repo = repo;
            _userss = repo.GetUsers();
        }
        public void OnGet()
        {

        }
        public void OnPost()
        {
        }
    }
}

Todo_App/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Todo_App.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Todo_App/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto shadow" style="border-bottom:solid; border-bottom-color:rgba(0,0,0,0.4);">
            <h3>Control panel</h3>
            <br />
            <div class="container">
                <div class="col">
                    
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ModalNew">New</button>
                    <button type="button" class="btn btn-dark" data-bs-toggle="collapse" data-bs-target="#Completed" aria-expanded="false" aria-controls="Completed">Completed</button>
                    <form method="post" asp-page-handler="DelAll">
                        <button type="submit" class="btn btn-warning">Delete all completed task</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="modal fade" id="ModalNew" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="NewTaskLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="NewTaskLabel">Add Task</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" asp-page-handler="Add">
                <div class="modal-body">
                    <div class="container m-3">

                        <div class="mb-2">
                            <span class="form-label" asp-validation-for="Title">Title</span>
                            <input class="form-control" asp-for="Title" />
                        </div>

                        <div class="mb-2">
                            <span class="form-label" asp-validation-for="Desc">Desc</span>
                            <input class="form-control" asp-for="Desc" />
                        </div>
                        
                        <div class="mb-2">
                            <span class="form-label" asp-validation-for="prio">Priority</span>
                            <select class="form-select" asp-for="prio">
                                <option value="0">low</option>
                                <option selected value="1">normal</option>
                                <option value="2">high</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container d-flex gap-4 justify-content-center">
    <div class="mb-3 col-6">
        <h3 class="text-center border-bottom">To-do</h3>
        <div class="d-flex justify-content-center flex-wrap">
            @foreach (var todo in Model.ToDoList)
            {
                if (!todo.IsCompleted == true)
                {
                    <div class="card col-7 mb-4 shadow" style=" box-shadow:black 10px">
                        <br />
                        <div class="card-body">

                            <h4 class="border-bottom card-title text-center">@todo.TaskTitle</h4>
                            <p class="text-center border-bottom">@todo.TaskDescription</p>
                            <p class="text-center">@todo.TaskPriority</p>
                            <footer>@todo.Created</footer>
                            <div class="modal-footer d-flex justify-content-center align-content-center flex-row">
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ModalEdit">Edit</button>
                                <form method="post" asp-page-handler="Delete">
                                    <input asp-for="GUid" type="hidden" value="@todo.GUID" />
                                    <button class="btn btn-primary" type="submit">Delete</button>
                                </form>
                                <form method="post" asp-page-handler="Comp">
                                    <input asp-for="GUid" type="hidden" value="@todo.GUID" />
                                    <button class="btn btn-primary" type="submit">Complete</button>
                                </form>
                            </div>
                        </div>
                        <div class="modal fade" id="ModalEdit" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="EditTaskLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="EditTaskLabel">Task Edit</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <form method="post" asp-page-handler="Edit">
                                        <div class="modal-body">
                                            <div class="container mb-3">

                                                <div class="flex-row mb-2">
                                                    <span class="form-label" asp-validation-for="Title">Title</span>
                                                    <input class="form-control" asp-for="Title" value="@todo.TaskTitle" />
                                                </div>

                                                <div class="flex-row mb-2">
                                                    <span class="form-label" asp-validation-for="Desc">Desc</span>
                                                    <input class="form-control" asp-for="Desc" value="@todo.TaskDescription" />
                                                </div>
                                                <div class="flex-row mb-2">
                                                    <span class="form-check-label" asp-validation-for="IsDone">complete</span>
                                                    <input class="form-check-input" asp-for="IsDone" type="checkbox" />
                                                </div>
                                                <div class="flex-row mb-2">
                                                    <span class="form-label" asp-validation-for="prio">Priority</span>
                                                    <select class="form-select" asp-for="prio">
                                                        <option value="0">low</option>
                                                        <option selected value="1">normal</option>
                                                        <option value="2">high</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <input asp-for="GUid" type="hidden" value="@todo.GUID" />
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <span class="border-bottom"></span>
                    </div>
                }
            }
        </div>
    </div>
    <div id="Completed" class="collapse mb-3 col-6">
        <h3 class="text-center border-bottom">Completed</h3>
        <div class="d-flex justify-content-center flex-wrap">
            @foreach (var todo in Model.ToDoList)
            {
                if (todo.IsCompleted == true)
                {
                    <div class="col-7 card mb-4 shadow" style="box-shadow:black 10px">
                        <br />
                        <div class=" card-body">
                            <h4 class="border-bottom card-title text-center">@todo.TaskTitle</h4>
                            <p class="text-center border-bottom">@todo.TaskDescription</p>
                            <p class="text-center">@todo.TaskPriority</p>
                            <footer>@todo.Created</footer>
                            <div class="modal-footer d-flex justify-content-center">
                                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ModalEdit">Edit</button>
                                <form method="post" asp-page-handler="Delete">
                                    <input asp-for="GUid" type="hidden" value="@todo.GUID" />
                                    <button class="btn btn-primary" type="submit">Delete</button>
                                </form>
                            </div>
                        </div>
                        <div class="modal fade" id="ModalEdit" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="EditTaskLabel" aria-hidden="true">

                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="EditTaskLabel">Task Edit</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <form method="post" asp-page-handler="Edit">
                                        <div class="modal-body">
                                            <div class="container mb-3">

                                                <input asp-for="GUid" type="hidden" value="@todo.GUID" />
                                                <div class="flex-row mb-2">
                                                    <span class="form-label" asp-validation-for="Title">Title</span>
                                                    <input class="form-control" asp-for="Title" value="@todo.TaskTitle" />
                                                </div>

                                                <div class="flex-row mb-2">
                                                    <span class="form-label" asp-validation-for="Desc">Desc</span>
                                                    <input class="form-control" asp-for="Desc" value="@todo.TaskDescription" />
                                                </div>
                                                <div class="flex-row mb-2">
                                                    <span class="form-check-label" asp-validation-for="IsDone">complete</span>
                                                    <input class="form-check-input" type="checkbox" checked asp-for="IsDone" />
                                                </div>
                                                <div class="flex-row mb-2">
                                                    <span class="form-label" asp-validation-for="prio">Priority</span>
                                                    <select class="form-select" asp-for="prio">
                                                        <option value="0">low</option>
                                                        <option value="1" selected>normal</option>
                                                        <option value="2">high</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <span class="border-bottom"> </span>
                    </div>
                }
            }
        </div>
    </div>
</div>

Todo_App/Pages/Login.cshtml
@page
@model Todo_App.Pages.LoginModel
@{
}

<!-- Section: Design Block -->
<section class=" text-center text-lg-start">
  <div class="card mb-3">
    <div class="row g-0 d-flex align-items-center">
      <div class="col-lg-4 d-none d-lg-flex">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" alt="Trendy Pants and Shoes"
          class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5" />
      </div>
      <div class="col-lg-8">
        <div class="card-body py-5 px-md-5">

            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" id="form2Example1" class="form-control" />
              <label class="form-label" for="form2Example1">Email address</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
              <input type="password" id="form2Example2" class="form-control" />
              <label class="form-label" for="form2Example2">Password</label>
            </div>
            <!-- Submit button -->
            <button type="button" class="btn btn-primary btn-block mb-4">Sign in</button>


        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Design Block -->

Todo_App/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Todo_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Todo_App.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Todo_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Todo_App - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>